version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Run Tests
          command: npm install && npm run test:unit

      - run:
          name: Deploy to Droplet
          command: date
