version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: Run Tests
          command: make circle-test
      - run:
          name: Deploy to Droplet
          command: date
