version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Node version: $(node --version)" && echo "npm version: $(npm --version)" && npm install && npm run test:unit
      - run:
          name: Deploy to Droplet
          command: date
