# Use postgres/example user/password credentials
version: '3.1'

services:
  wedding-db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - wedding-data:/var/lib/postgresql/data
  db-setup:
    image: sconnel42/app-base:latest
    container_name: db-setup
    depends_on:
      - wedding-db
    environment:
      NODE_ENV: "production"
      USE_PROD: ${USE_PROD}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: wedding-db
      DB_PORT: 5432
      DB_STRING: ${DB_STRING}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    command: ["/bin/bash","scripts/setup.sh"]

volumes:
  wedding-data:

networks:
  default:
    external:
      name: ${DOCKER_NET}
