# Use postgres/example user/password credentials
version: '3.1'

services:
  wedding-db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - wedding-data:/var/lib/postgresql/data
  wedding-db-setup:
    image: sconnel42/app-base
    environment:
      USE_PROD: ${USE_PROD}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_STRING: ${DB_STRING}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    command: ["/bin/bash","scripts/setup.sh"]
  web-server:
    image: sconnel42/web-server
    container_name: web-server
    environment:
      NODE_ENV: "production"
      PROJECT_ROOT: ${PROJECT_ROOT}
      PORT: ${SERVER_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB_DIALECT: ${DB_DIALECT}
      USE_PROD: ${USE_PROD}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      TWILIO_API_KEY: ${TWILIO_API_KEY}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      ADMIN_PHONE_NUMBER: ${ADMIN_PHONE_NUMBER}
    ports:
      - "8080:80"

volumes:
  wedding-data:

networks:
  default:
    external:
      name: ${DOCKER_NET}
