# Use postgres/example user/password credentials
version: '3.1'

services:
  wedding-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - wedding-data:/var/lib/postgresql/data
  db-setup:
    image: sconnel42/app-base:latest
    container_name: db-setup
    depends_on:
      - wedding-db
    environment:
      NODE_ENV: "production"
      USE_PROD: ${USE_PROD}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: "wedding-db"
      DB_PORT: "5432"
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    command: ["/bin/bash","scripts/setup.sh"]
  web-server:
    image: sconnel42/web-server:latest
    container_name: web-server
    environment:
      NODE_ENV: "production"
      PROJECT_ROOT: ${PROJECT_ROOT}
      PORT: ${SERVER_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB_DIALECT: ${DB_DIALECT}
      USE_PROD: ${USE_PROD}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      TWILIO_API_KEY: ${TWILIO_API_KEY}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      ADMIN_PHONE_NUMBER: ${ADMIN_PHONE_NUMBER}
    ports:
      - "3000"
  wedding-proxy:
    image: sconnel42/wedding-proxy:latest
    container_name: wedding-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot-data/certbot/conf:/etc/letsencrypt
      - ./certbot-data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot-data/certbot/conf:/etc/letsencrypt
      - ./certbot-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  wedding-data:

networks:
  default:
    external:
      name: ${DOCKER_NET}
